"""add phone number

Revision ID: 011559b38a89
Revises: 40aa1b5e46da
Create Date: 2022-08-29 15:50:48.309132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011559b38a89'
down_revision = '40aa1b5e46da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
